# Site settings
title: REBIPP - Plant-Pollinator Interactions
description: Website for the REBIPP Plant-Pollinator Interactions standard.
#url: "https://dwc.tdwg.org"

navbar:
  left:
  - text: Terms
    href: terms/
  # - text: Guides
    # menu:
    # - text: Simple REBIPP standard
      # href: simple/
    # - text: Text
      # href: text/
    # - text: XML
      # href: xml/
    # - text: RDF
      # href: rdf/
  # - text: Namespace policy
    # href: namespace/
  right:
  - text: GitHub
    href: https://github.com/BioComp-USP/rebipp-data-standard

js: >-
  $(document).ready(function() {
      // In quick reference guide: add divider in sidebar after UseWithIRI
      $("a[href='#usewithiri']", "#theme-sidebar-nav").parent().addClass("theme-divider-below");
  });

# Build settings
markdown: kramdown
# theme: tdwg-theme-jekyll
remote_theme: BioComp-USP/tdwg-theme-jekyll
plugins:
  - jekyll-feed

#theme: tdwg-theme-jekyll
